name: CI Pipeline

# on:
#  push:
#    branches: ['main']
#  pull_request:
#    branches: ['main']

jobs:
  test:                                                     # ************************** test 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: .
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pytest tests/ -v --cov=app --cov-report=term --cov-report=xml

  deploy:                                                   # ************************** deploy 
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-deploy]')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://jackobess:$HF_TOKEN@huggingface.co/spaces/jackobess/OC_Projet5
          git push hf main --force